### PR TITLE
Remoduling

### PR DESCRIPTION
**Pull request by zegelin**
Moves sidecar specific code out of common module:
- Operations (for now)
- Jersey HTTP Server code (very sidecar specific right now)
- Move CLI options back into main entrypoint class.

Cleaned up the common PicoCLI TypeHandlers:
- Replaced `HostnamePortConverter` with `InetSocketAddressTypeConverter` (from cassandra-exporter)
- Added `ServerInetSocketAddressTypeConverter` for CLI arguments that represent listening server sockets.
- Modified `JMXServiceURLTypeConverter` to support both JMX Service URLs and address:port combos

### CODE REVIEW

**Comment by zegelin** [comment]
The intent for the `common` module was to start to build up a collection of classes and utility functions that end up being used in _every_ Instaclustr Java project -- the backups codebase, the sassandra-exporter, this operator's sidecar, future sidecars, etc. We'd eventually pull this out into a separate project.

A few sidecar specific things have crept into the common module -- this PR moves them back.

**Comment by alourie** [comment]
LGTM. Also, does it include the content of the #188 as well?

**Comment by zegelin** [comment]
@alourie It did, because I'd branched of a `repackaging` branch. But I've merged that PR, and now this is up-to-date.

**Comment by alourie** [comment]
:+1:

**Pull request merged**
