### PR TITLE
add finalizers for cassandra pods

### PR DESCRIPTION
**Pull request by srteam2020**
Addressing https://github.com/instaclustr/cassandra-operator/issues/398
Added finalizer for Cassandra pod to delete PVC before deletion

### CODE REVIEW

**Comment by srteam2020** [comment]
Build fails with `E: Version '11.0.8+10-1~deb10u1' for 'openjdk-11-jre-headless' was not found` from CI.
Looks unrelated to the patch.

**Comment by smiklosovic** [comment]
Hi @srteam2020 

unfortunately this does not work as I would expect. I am not sure if I am doing something wrong but there is this issue:

spec:
  deletePVCs: true

1. start a cluster
2. stop a cluster

My nodes will hang on Terminating and they will never trully terminate.

I have to do 

```
kubectl patch pod cassandra-test-cluster-dc1-west1-a-0 -p '{"metadata":{"finalizers":null}}'
kubectl patch pod cassandra-test-cluster-dc1-west1-b-0 -p '{"metadata":{"finalizers":null}}'
```

and this terminates them

**Comment by srteam2020** [comment]
Seems that the finalizers of the pods are not properly removed when deleting the whole cluster. Let me fix it.

**Comment by srteam2020** [comment]
@smiklosovic 
It is caused by `finalizeIfNecessary` not removing finalizers for cassandra pods.
Just updated the patch. Should work now.

**Pull request closed without merging**
