### PR TITLE
Cassandra has many names

### LINKED ISSUE #57: Tag `cassandra` image with Cassandra version
Curently, `build` & `build-all` tag images with the repo short hash & `latest`. This is useful for development.

Ideally the Cassandra image should be tagged with the version of C* it represents, e.g. `3.2.11`.
This makes it obvious what version is contained within, and will be necissary once we need to support multiple C* versions.

### PR DESCRIPTION
**Pull request by alourie**
Closes #57 

Signed-off-by: Alex Lourie <djay.il@gmail.com>

### CODE REVIEW

**Comment by smiklosovic** [comment]
@alourie this means that everytime we change something in Cassandra image, even there are not any other changes elsewhere, we will be forced to do a release, @benbromhead @zegelin are we ok with that?

**Comment by alourie** [comment]
@smiklosovic Yea, I'd agree, but remember that we do a lot of customisations in there _for_ the operator specifically. We're not just wrapping the Cassandra itself, we're actually doing some operator-specific thing....unless we don't.

Either way, how would you suggest tagging this image then? We currently have no other mechanism to release our container images, so if there is any other idea, I'm all for it :-)

**Comment by mmonemali** [comment]
I'm just curious what things in the operator depends on the Cassandra version that is running, and if these things can be eliminated/refactored somehow.

**Comment by smiklosovic** [comment]
@mmonemali virtually none. The whole communication to Cassandra is done only via its sidecar container via JMX. Some method _might_ change in JMX across versions but the differences should be negligible if any. If switch is done between 3.x versions, it should be just fine. Not sure if method signatures for JMX in 4.0 differ ... Apart from this, it should be fine. Maybe some configuration options for JVM? I can imagine that can be different little bit e.g. the configuration of garbage collectors etc ... Some options can be replaced by fragment mechanism already.

**Pull request closed without merging**
